---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: icecream
      tier: frontend
  template:
    metadata:
      labels:
        app: icecream
        tier: frontend
    spec:
      containers:
        - name: frontend
          image: sriramyaganni/icecreams-website
          ports:
            - containerPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: icecream
      tier: backend
  template:
    metadata:
      labels:
        app: icecream
        tier: backend
    spec:
      containers:
        - name: backend
          image: sriramyaganni/icecreams-website
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URL
              value: "mongodb://mongo:27017/icecream"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: icecream
      tier: mongo
  template:
    metadata:
      labels:
        app: icecream
        tier: mongo
    spec:
      containers:
        - name: mongo
          image: mongo
          ports:
            - containerPort: 27017

---
apiVersion: v1
kind: Service
metadata:
  name: icecream-lb
spec:
  type: LoadBalancer
  selector:
    app: icecream
  ports:
    - name: frontend
      port: 80
      targetPort: 80

    - name: backend
      port: 3000
      targetPort: 3000

    - name: mongo
      port: 27017
      targetPort: 27017
