version: "3.8"

services:

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: .
    container_name: icecream-backend
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://mongodb:27017/icecream
    depends_on:
      - mongodb
